"""updae order

Revision ID: b7e89a50639a
Revises: 9aebb59534db
Create Date: 2024-04-13 11:23:29.097599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e89a50639a'
down_revision = '9aebb59534db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'running', 'cancelled', 'completed', name='order_status_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
